CREATE TABLE IF NOT EXISTS `holding` (
  createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deletedAt TIMESTAMP NULL,
  `id` VARCHAR(36) PRIMARY KEY NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `cik` VARCHAR(20) NOT NULL,
  `cusip` VARCHAR(20) NOT NULL,
  `investorId` VARCHAR(36) NOT NULL,
  `stockId` VARCHAR(36) NOT NULL,
  `value` BIGINT NOT NULL,
  `shares` BIGINT NOT NULL,
  `year` INT NOT NULL,
  `quarter` INT NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;