CREATE TABLE IF NOT EXISTS `rank` (
  createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  id VARCHAR(36) PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL,
  tickers TEXT NOT NULL,
  type INT NOT NULL,
  year INT NOT NULL,
  quarter INT NOT NULL,
  `rank` INT NOT NULL,
  value BIGINT NOT NULL,
  investorId VARCHAR(36) NOT NULL,
  lastUpdatedAt DATETIME NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;