CREATE TABLE IF NOT EXISTS filing (
  createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  id INT AUTO_INCREMENT PRIMARY KEY,
  investorId VARCHAR(36) NOT NULL,
  type VARCHAR(20) NOT NULL,
  accessionNumber VARCHAR(50) NOT NULL,
  filledOn DATE NOT NULL,
  reportedOn DATE NOT NULL,
  link VARCHAR(255) NOT NULL,
  year INT NOT NULL,
  quarter INT NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
