// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/changchanghwang/wdwb_back/internal/libs/db"
	"github.com/changchanghwang/wdwb_back/internal/libs/sec-client"
	"github.com/changchanghwang/wdwb_back/internal/server"
	"github.com/changchanghwang/wdwb_back/internal/services/stocks/application"
	"github.com/changchanghwang/wdwb_back/internal/services/stocks/infrastructure"
	"github.com/changchanghwang/wdwb_back/internal/services/stocks/presentation"
)

// Injectors from wire.go:

func InitializeServer() (*server.Server, error) {
	gormDB := db.Init()
	stockRepository := infrastructure.New(gormDB)
	secClientSecClient := secClient.New()
	stockService := application.New(stockRepository, gormDB, secClientSecClient)
	stockController := presentation.New(stockService)
	serverServer := server.New(stockController)
	return serverServer, nil
}
