basePath: /
definitions:
  base.ErrorResponse:
    properties:
      errorMessage:
        example: error message
        type: string
    type: object
  commands.RankCommand:
    properties:
      quarter:
        description: 1, 2, 3, 4 optional
        type: integer
      year:
        description: "2024"
        type: integer
    required:
    - year
    type: object
  domain.Rank:
    properties:
      id:
        type: string
      investorId:
        type: string
      lastUpdatedAt:
        type: string
      name:
        type: string
      quarter:
        type: integer
      rank:
        type: integer
      tickers:
        items:
          type: string
        type: array
      type:
        $ref: '#/definitions/domain.RankType'
      value:
        type: integer
      year:
        type: integer
    type: object
  domain.RankType:
    enum:
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    type: integer
    x-enum-varnames:
    - TopBuyQuarter
    - TopSellQuarter
    - TopHoldingQuarter
    - TopBuyYear
    - TopSellYear
    - TopHoldingYear
  response.HoldingListResponse:
    properties:
      count:
        type: integer
      items:
        items:
          $ref: '#/definitions/response.HoldingRetrieveResponse'
        type: array
    type: object
  response.HoldingRetrieveResponse:
    properties:
      id:
        description: holding cik
        example: "0001067983"
        type: string
      investorId:
        description: investor id
        example: 123e4567-e89b-12d3-a456-426614174000
        type: string
      name:
        description: holding name
        example: Company Name
        type: string
      quarter:
        description: holding quarter
        example: 1
        type: integer
      shares:
        description: number of stock shares
        example: 1000
        type: integer
      translated:
        description: whether the holding name is translated
        example: true
        type: boolean
      value:
        description: total amount of holding value
        example: 1000000
        type: integer
      year:
        description: holding year
        example: 2021
        type: integer
    type: object
  response.InvestorListResponse:
    properties:
      count:
        type: integer
      items:
        items:
          $ref: '#/definitions/response.InvestorRetrieveResponse'
        type: array
    type: object
  response.InvestorRetrieveResponse:
    properties:
      cik:
        description: investor company index key
        example: "1234567890"
        type: string
      companyName:
        description: investor company name
        example: Company Name
        type: string
      holdingValue:
        description: total value of holdings
        example: 1000000
        type: integer
      id:
        description: investor id
        example: 123e4567-e89b-12d3-a456-426614174000
        type: string
      name:
        description: investor name
        example: John Doe
        type: string
      url:
        description: investor image url
        example: https://s3.amazonaws.com/image/image.png
        type: string
    type: object
  response.RankResponse:
    properties:
      topBuyQuarter:
        description: buy ranking per quarter
        items:
          $ref: '#/definitions/domain.Rank'
        type: array
      topBuyYear:
        description: buy ranking per year
        items:
          $ref: '#/definitions/domain.Rank'
        type: array
      topHoldingQuarter:
        description: holding ranking per quarter
        items:
          $ref: '#/definitions/domain.Rank'
        type: array
      topHoldingYear:
        description: holding ranking per year
        items:
          $ref: '#/definitions/domain.Rank'
        type: array
      topSellQuarter:
        description: sell ranking per quarter
        items:
          $ref: '#/definitions/domain.Rank'
        type: array
      topSellYear:
        description: sell ranking per year
        items:
          $ref: '#/definitions/domain.Rank'
        type: array
    type: object
info:
  contact:
    email: window95pill@gmail.com
    name: API Support
  description: API Server for wdwb
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: wdwb API
  version: "1.0"
paths:
  /holdings:
    get:
      consumes:
      - application/json
      description: Get holdings list
      parameters:
      - in: query
        name: investorId
        required: true
        type: string
      - in: query
        name: limit
        type: integer
      - in: query
        name: page
        type: integer
      - in: query
        name: quarter
        required: true
        type: integer
      - in: query
        name: year
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Successfully get holdings list
          schema:
            $ref: '#/definitions/response.HoldingListResponse'
        "400":
          description: Bad request
          schema:
            allOf:
            - $ref: '#/definitions/base.ErrorResponse'
            - properties:
                errorMessage:
                  type: string
              type: object
        "500":
          description: Internal server error
          schema:
            allOf:
            - $ref: '#/definitions/base.ErrorResponse'
            - properties:
                errorMessage:
                  type: string
              type: object
      summary: Get holdings list
      tags:
      - holdings
  /investors:
    get:
      consumes:
      - application/json
      description: Get investors list
      produces:
      - application/json
      responses:
        "200":
          description: Successfully get investors list
          schema:
            $ref: '#/definitions/response.InvestorListResponse'
        "400":
          description: Bad request
          schema:
            allOf:
            - $ref: '#/definitions/base.ErrorResponse'
            - properties:
                errorMessage:
                  type: string
              type: object
        "500":
          description: Internal server error
          schema:
            allOf:
            - $ref: '#/definitions/base.ErrorResponse'
            - properties:
                errorMessage:
                  type: string
              type: object
      summary: Get investors list
      tags:
      - investors
  /investors/{id}:
    get:
      consumes:
      - application/json
      description: Retrieve investor
      parameters:
      - description: Investor ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Successfully retrieve investor
          schema:
            $ref: '#/definitions/response.InvestorRetrieveResponse'
        "400":
          description: Bad request
          schema:
            allOf:
            - $ref: '#/definitions/base.ErrorResponse'
            - properties:
                errorMessage:
                  type: string
              type: object
        "404":
          description: Not found
          schema:
            allOf:
            - $ref: '#/definitions/base.ErrorResponse'
            - properties:
                errorMessage:
                  type: string
              type: object
        "500":
          description: Internal server error
          schema:
            allOf:
            - $ref: '#/definitions/base.ErrorResponse'
            - properties:
                errorMessage:
                  type: string
              type: object
      summary: Retrieve investor
      tags:
      - investors
  /ranks:
    get:
      consumes:
      - application/json
      description: Rank
      parameters:
      - description: Rank command
        in: body
        name: command
        required: true
        schema:
          $ref: '#/definitions/commands.RankCommand'
      produces:
      - application/json
      responses:
        "200":
          description: Successfully retrieve investor
          schema:
            $ref: '#/definitions/response.RankResponse'
        "400":
          description: Bad request
          schema:
            allOf:
            - $ref: '#/definitions/base.ErrorResponse'
            - properties:
                errorMessage:
                  type: string
              type: object
        "404":
          description: Not found
          schema:
            allOf:
            - $ref: '#/definitions/base.ErrorResponse'
            - properties:
                errorMessage:
                  type: string
              type: object
        "500":
          description: Internal server error
          schema:
            allOf:
            - $ref: '#/definitions/base.ErrorResponse'
            - properties:
                errorMessage:
                  type: string
              type: object
      summary: Rank
      tags:
      - ranks
swagger: "2.0"
