basePath: /
definitions:
  base.BaseResponse:
    properties:
      data: {}
    type: object
  base.ErrorResponse:
    properties:
      data:
        example: error message
        type: string
    type: object
  response.ListResponse:
    properties:
      count:
        type: integer
      items:
        items:
          $ref: '#/definitions/response.RetrieveResponse'
        type: array
    type: object
  response.RetrieveResponse:
    properties:
      cik:
        example: "1234567890"
        type: string
      companyName:
        example: Company Name
        type: string
      holdingValue:
        example: 1000000
        type: integer
      id:
        example: 123e4567-e89b-12d3-a456-426614174000
        type: string
      name:
        example: John Doe
        type: string
    type: object
info:
  contact:
    email: window95pill@gmail.com
    name: API Support
  description: API Server for wdwb
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: wdwb API
  version: "1.0"
paths:
  /investors:
    get:
      consumes:
      - application/json
      description: Get investors list
      produces:
      - application/json
      responses:
        "200":
          description: Successfully get investors list
          schema:
            allOf:
            - $ref: '#/definitions/base.BaseResponse'
            - properties:
                data:
                  $ref: '#/definitions/response.ListResponse'
              type: object
        "400":
          description: Bad request
          schema:
            allOf:
            - $ref: '#/definitions/base.ErrorResponse'
            - properties:
                data:
                  type: string
              type: object
        "500":
          description: Internal server error
          schema:
            allOf:
            - $ref: '#/definitions/base.ErrorResponse'
            - properties:
                data:
                  type: string
              type: object
      summary: Get investors list
      tags:
      - investors
swagger: "2.0"
